---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-example-octodex
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: aws-example-octodex
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - name: aws-example-octodex
        image: 438296044123.dkr.ecr.eu-west-1.amazonaws.com/example-eks:5dd961534f6845355d125ee2f82f50df11386623
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
